spring.application.name=telcolite

telcolite.operator-name=TelcoLite BiH
telcolite.currency=KM
telcolite.vat-rate=0.17
telcolite.discount.type=student

spring.datasource.url=jdbc:postgresql://localhost:5432/telcolite
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true